# Theme Configuration for Hexo Researcher Theme

# Basic Information
avatar: /images/avatar.jpg
favicon: /images/favicon.ico

# Menu Configuration
# Add or remove menu items as needed
menu:
  - name: Publications
    url: /publications/
    icon: fa-solid fa-newspaper
  - name: Projects
    url: /projects/
    icon: fa-solid fa-project-diagram
  - name: CV
    url: /cv/
    icon: fa-solid fa-id-card
  - name: Talks
    url: /talks/
    icon: fa-solid fa-microphone
  - name: Notes
    url: /notes/
    icon: fa-solid fa-sticky-note
  - name: Contact
    url: /contact/
    icon: fa-solid fa-envelope

# CV Download
# Provide a link to download your CV or put the pdf file in the 'source/files' folder of your Hexo site and use a relative path.
cv:
  #download_link: https://www.nature.com/articles/d41586-025-01882-7.pdf 
  # or
  download_link: /files/cv-template.pdf

# CV Sections Configuration
# Set to false to hide any section
cv_sections:
  education: true
  experience: true
  skills: true
  awards: true
  languages: true
  teaching: true

# About
about:
  I am a researcher passionate about artificial intelligence and computational biology.
  My work focuses on leveraging machine learning to solve real-world problems.
  <br><br>
  Outside of research, I enjoy hiking, writing, and coffee brewing.

# Academic Profiles
academic_profiles:
  google_scholar: https://scholar.google.com/citations?user=YOUR_ID
  orcid: https://orcid.org/YOUR_ID
  researchgate: https://www.researchgate.net/profile/YOUR_ID
  github: https://github.com/YOUR_ID
  linkedin: https://linkedin.com/in/YOUR_ID
  twitter: https://twitter.com/YOUR_ID

# Contact
contact:
  email: your.email@example.com
  phone: "+0 123 456789"
  address: "Room 123, Department of Biology, University of Example, 12345 City, Country"
  google_map: "https://maps.app.goo.gl/xxxxxxxxxxx"
  office_hours: "Mon–Fri 10:00–16:00"

# Push/Ab
# Google adsense
google_adsense: your_google_adsense_id
# Umami
umami_id: your_umami_id
# Baidu_tongji
baidu_tongji: your_baidu_tongji_id

# daisyui themes
daisyui:
  default: light
  enabled:
    - light
    - dark
    - cupcake
    - bumblebee
    - emerald
    - corporate
    - synthwave
    - retro
    - cyberpunk
    - valentine
    - halloween
    - garden
    - forest
    - aqua
    - lofi
    - pastel
    - fantasy
    - wireframe
    - black
    - luxury
    - dracula
    - cmyk
    - autumn
    - business
    - acid
    - lemonade
    - night
    - coffee
    - winter
    - dim
    - nord
    - sunset
    - caramellatte
    - abyss
    - silk